// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPyOy8cB8SUKMFlce3HSX8xlssQiJDo4',
    appId: '1:567085993093:web:0d46b667282625f17fedec',
    messagingSenderId: '567085993093',
    projectId: 'ecommerce-c94e4',
    authDomain: 'ecommerce-c94e4.firebaseapp.com',
    storageBucket: 'ecommerce-c94e4.firebasestorage.app',
    measurementId: 'G-11L8X1K6K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfSFqeVCQg6flr2DOiqMqibBjXrOjE_1w',
    appId: '1:567085993093:android:30571e02d24b3fb87fedec',
    messagingSenderId: '567085993093',
    projectId: 'ecommerce-c94e4',
    storageBucket: 'ecommerce-c94e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4sPfXXni9FOJeSlM8YOpQ2VH4TTaoNhQ',
    appId: '1:567085993093:ios:7cca3aeb691a9f8e7fedec',
    messagingSenderId: '567085993093',
    projectId: 'ecommerce-c94e4',
    storageBucket: 'ecommerce-c94e4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
